# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    #listing_template: tag-listing.twig #custom template

chapters:
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    options: { main: "The main chapter", meta: "Meta Chapter", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]

iAmPages:
    name: iAm
    slug: iAmPages
    behaves_like: grouping
    options: [a teen, a college student, employed, a business owner, a couple, a parent, a home owner, in crisis, retired]
    

programs:
    name: programs
    slug: programs
    behaves_like: grouping
    options: [Reality Store, Money Smart Week, Free Tax Assistance, Money Strong, FAFSA Help, Great Piggy Bank Pageant]

topics:
    name: topics
    slug: topics
    behaves_like: grouping
    options: [Budgeting, Building Credit, Health Care, Money Management, Debt Management, Family Finance]

events:
    name: events
    slug: events
    behaves_like: grouping
    options: [Events]

tools:
    name: tools
    slug: tools
    behaves_like: grouping
    options: [Loan Calulator, Mortgage Calulator]

newsletter:
    name: newsletter
    slug: newsletter
    behaves_like: grouping
    options: [Newsletter]

weAre:
    name: weAre
    slug: weAre
    behaves_like: grouping
    options: [Overview, Members, Mission]

needHelp:
    name: needHelp
    slug: needHelp
    behaves_like: grouping
    options: [Need Help]

aside:
    name: aside
    slug: aside
    behaves_like: grouping
    options: [aside]

sponsor:
    name: sponsor
    slug: sponsor
    behaves_like: grouping
    options: [sponsor]

sidebar:
    name: sidebar
    slug: sidebar
    behaves_like: grouping
    options: [ sidebar ]
